stages:
    - build_ui
    - build
    - deploy

build:admin_ui:
    only:
        - master
        - feature/analytics
    stage: build_ui
    image: kkarczmarczyk/node-yarn:8.0
    script:
        - sh build-admin-ui.sh
    artifacts:
        paths:
            - src/Kasbah.Web.Management.UI/dist/
    cache:
        paths:
            - src/Kasbah.Web.Management.UI/node_modules/

build:dotnet:
    only:
        - master
        - feature/analytics
    stage: build
    image: microsoft/dotnet:2-sdk
    dependencies:
    - build:admin_ui
    script:
        - sh build-dotnet.sh
    artifacts:
        paths:
        - artifacts/

deploy:
    only:
        - master
        - feature/analytics
    stage: deploy
    script:
        - sh deploy.sh
