build:admin_ui:
    stage: build_ui
    image: node:6
    script:
        - sh build-admin-ui.sh
    artifacts:
        paths:
        - src/Kasbah.Web.ContentManagement.UI/dist/

build:dotnet:
    stage: build
    image: microsoft/dotnet
    dependencies:
    - build:admin_ui
    before_script:
        - ls -la
    script:
        - sh build-dotnet.sh
    artifacts:
        paths:
        - artifacts/
