stages:
    - build_ui
    - build
    - deploy

build:admin_ui:
    only:
        - master
        - version/3.0
    stage: build_ui
    image: kkarczmarczyk/node-yarn:6.9
    script:
        - sh build-admin-ui.sh
    artifacts:
        paths:
        - src/Kasbah.Web.Management.UI/dist/

build:dotnet:
    only:
        - master
        - version/3.0
    stage: build
    image: microsoft/dotnet:2-sdk
    dependencies:
    - build:admin_ui
    script:
        - sh build-dotnet.sh
    artifacts:
        paths:
        - artifacts/

deploy:
    only:
        - master
        - version/3.0
    stage: deploy
    script:
        - sh deploy.sh
