stages:
    - build_ui
    - build
    - deploy

build:admin_ui:
    only: master
    stage: build_ui
    image: kkarczmarczyk/node-yarn:6.9
    script:
        - sh build-admin-ui.sh
    artifacts:
        paths:
        - src/Kasbah.Web.ContentManagement.UI/dist/

build:dotnet:
    only: master
    stage: build
    image: microsoft/dotnet:1.1.1-sdk-1.0.0
    dependencies:
    - build:admin_ui
    script:
        - sh build-dotnet.sh
    artifacts:
        paths:
        - artifacts/

deploy:
    only: master
    stage: deploy
    script:
        - sh deploy.sh
